aruco_pose:
  ros__parameters:
    cam_translation:
      x: 0.549 # robot location w.r.t to camera in 4
      y: -0.392 
      z: 0.08 
    cam_rotation: # These are expressed in RPY angles
      alpha: 00.0
      beta: 90.0
      gamma: 180.0
    camera_tf_frame: 'camera_base'
    sample_name: 'sample_1'
    pre_pickup_location: 
      name: 'pre_pickup'
      x_adj: 0.0
      y_adj: 0.0
      z_adj: 0.08
    offset_on_marker_x: -0.005
    offset_on_marker_y: 0.0
    fiducial_marker_family: 'DICT_APRILTAG_36h11'
    physical_marker_size: 0.02665 # 0.032 #  #
    number_of_observations: 10 # size of the moving window for the median filter
    