pdf_beamtime_server:
  ros__parameters:
    home_angles: [0.0, -1.5708, 0.00, -1.5708, 0.0, 3.14159] #For real robot
    pickup_approach_angles: [3.81755, -1.1435397, 2.66459, -1.5374605, 0.700226, 3.1415926]
    gripper_present: true
    joint_acc_vel_scaling_factor: 0.1
    joint_constraints:
      joint_name: 'wrist_3_joint'
      joint_position: 3.14159
      upper_limit: 0.78539
      lower_limit: 0.78539
