mesh_files:

  hande_base:
    visual:
      mesh:
        package: ur3e_hande_robot_description
        path: meshes/hande/visual/hand-e.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur3e_hande_robot_description
        path: meshes/hande/collision/hand-e.stl

  left_finger:
    visual:
      mesh:
        package: ur3e_hande_robot_description
        path: meshes/hande/visual/finger_1.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur3e_hande_robot_description
        path: meshes/hande/collision/finger_1.stl

  right_finger:
    visual:
      mesh:
        package: ur3e_hande_robot_description
        path: meshes/hande/visual/finger_2.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur3e_hande_robot_description
        path: meshes/hande/collision/finger_2.stl
          